mx:
  xyzrd-test:
    server:
      host: 10.30.2.221
      port: 7778
      secure: true
      skipVerify: true
      timeout: 20s
      reconnectDelay: 30s
      maxError: 5
    login:
      user: smsgate
      password: "9185"
    phones:
      defaultPrefix: "1"
      from:
      - "14086751455"
      - "14086751475"
    defaultJID: "44086340573989457"
smsgate:
  smpp:
    address:
    - 67.231.1.30:2775
    - 67.231.4.201:2775
    systemId: Zultys
    password: unmQF932
    enquireDuration: 30s
    reconnectDelay: 30s
    maxError: 5
    maxParts: 8
  messageTemplates:
    noPhone: No phone in the beginning of the message
    incorrect: 'Invalid phone number: %q'
    accepted: SMS sended to %q
    delivered: SMS delivered to %q
    error: 'SMS send error: %s'
    incoming: |-
      SMS from %q
      %s
  mySqlLog: root@/mxsms?charset=utf8
  zabbixHost: BOS-MXV-SMS-GW1
