mx:
  xyzrd:
    server:
      host: voip.xyzrd.com
      port: 7778
      secure: true
      skipVerify: true
      timeout: 5s
      reconnectDelay: 2s
    login:
      user: d3
      password: "9185"
    phones:
      defaultPrefix: "7"
      from:
      - "14086751455"
      - "14086751475"
smpp:
  address:
  - 67.231.1.30:2775
  - 67.231.4.201:2775
  systemId: Zultys
  password: unmQF932
  enquireDuration: 1m0s
  maxParts: 3
